### ISSUE TITLE
Call Callback in case of Failure or Canceled

### ISSUE THREAD

**Issue by barbaragomes** [taltultc/react-native-mov-to-mp4#1]
Would be nice if the callback gets called with a different response in case of failure or cancelation.

**Comment by taltultc** [comment]
I will add error response and video quality parameter

**Comment by barbaragomes** [comment]
Nice! Thanks!

**Comment by pedrofmlopes** [comment]
+1

**Comment by Andorbal** [comment]
I just created a pull request to use promises, which does reject when there's a failure.  It doesn't give the actual error yet, though.

#4

**Comment by taltultc** [comment]
Hey @Andorbal ,
Thanks for the pull request.
I hope i will have time to update this plugin with correct errors from the native.

**Comment by Andorbal** [comment]
Looks like the actual error may be pretty straightforward to pull in.  I can give it a go tonight.
