### ISSUE TITLE
Latest version does not match npm

### ISSUE THREAD

**Issue by Kuhne1** [taltultc/react-native-mov-to-mp4#17]
When I run npm install react-native-mov-to-mp4 --save
I get version 0.2.1

While if you install via the Github link you get the latest version 0.2.2 (with the pod spec)

If you could update this, please :) 

Thanks!

**Comment by taltultc** [comment]
Hi @Kuhne1 
Sorry for the delay, Done.
https://www.npmjs.com/package/react-native-mov-to-mp4
