### ISSUE TITLE
it not working 

### ISSUE THREAD

**Issue by nguyenductoan1995** [taltultc/react-native-mov-to-mp4#20]
I tried to install it and it didn't work

**Comment by etsraphael** [comment]
Same for me

**Comment by nguyenductoan1995** [comment]
> Same for me

you can using  ```yarn add https://github.com/taltultc/react-native-mov-to-mp4.git```
it working

**Comment by taltultc** [comment]
Hi @etsraphael @nguyenductoan1995 
I have updated the npm.
https://www.npmjs.com/package/react-native-mov-to-mp4
