### ISSUE TITLE
AVAssetExportSessionStatusFailed

### ISSUE THREAD

**Issue by NISHANTSINGHREWSAN** [taltultc/react-native-mov-to-mp4#3]
hi i am getting this status, i am using 24 version of react-native

here are my code snippet,

let context = this, 
        options = {
            mediaType: 'mixed',
            quality: 1,
            thumbnail: {
              maxWidth: 300,
              maxHeight: 300,
              cover: true
            },
            allowsEditing: false,
            noData:true,
            storageOptions: {
              skipBackup: true,
              path: 'images'
            }
          };

    ImagePicker.launchImageLibrary(options, (response) => {
     //  console.log('Response = ', response);
     if(response.error=='Photo library permissions not granted' || response.error=='Camera permissions not granted'){
      alert(Connection.ErrMsgForGallery(response.error));  
    }
      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } 
      else {
        this.setState({fileType:'',profileUrl:''});
        var ext = response.uri.substr(response.uri.lastIndexOf('.') + 1);
       // console.log("ext dsfsd", ext);
        console.log("response ", response.uri, MovToMp4);

        if(ext == 'MOV'){
          var filename = Date.now().toString();
            **MovToMp4.convertMovToMp4(response.uri, filename + ".mp4", function (results) {
              //here you can upload the video...
              console.log(" abc", results);
            });**

          promiseArr.push(RNAssetThumbnail.generateThumbnail(response.origURL, 220, 220));
          Promise.all(promiseArr).then(thumbnails => { 
           // console.log("thumbnails[0] ", thumbnails[0]);
            this.setState({
              fileType: thumbnails[0]
            });
          });

          this.setState({
            profileUrl: response.uri,
          })
        }
        else{
          this.setState({
            profileUrl: response.uri,
            fileType: 'image',
          })
        }
        
      }
    });
  },

i make it bold to the mehod i used

**Comment by taltultc** [comment]
Hi @NISHANTSINGHREWSAN 
Did you check that response.uri give you correct path to the file?
