### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by babydanger** [taltultc/react-native-mov-to-mp4#6]
when i try convert video .mov to mp4, i have this error
im using react-native: "^0.48.3"
here is my code: 

```
 MovToMp4.convertMovToMp4('file:///Users/Hiepuh/Library/Developer/CoreSimulator/Devices/D2313230-070A-48B3-A845-5803D4F489AE/data/Containers/Data/Application/7CF0373B-A447-435A-9AB4-659A91A0D73A/Documents/images/trim.36AA0023-6837-4F21-BEAD-67FD45DDF46D.MO', 'abcdef.mp4').then((results) => {
                console.log(results);
            }).catch(err => console.error(err));
```

**Comment by taltultc** [comment]
Maybe your file extension is missing? (mov)
file:///Users/Hiepuh/Library/Developer/CoreSimulator/Devices/D2313230-070A-48B3-A845-5803D4F489AE/data/Containers/Data/Application/7CF0373B-A447-435A-9AB4-659A91A0D73A/Documents/images/trim.36AA0023-6837-4F21-BEAD-67FD45DDF46D.MO

**Comment by babydanger** [comment]
aw, i copy missing last character, my file is .mov type.
but cant convert :(
i using react-native-image-picker to get file path
