### ISSUE TITLE
The operation could not be completed

### ISSUE THREAD

**Issue by ttrubel** [taltultc/react-native-mov-to-mp4#7]
Trying to convert mov to mp4, app gives an error: `The operation could not be completed`.

My file path look like `assets-library://asset/asset.MOV?id=1C8F1986-8C2A-407C-8A33-1A44F878FDCB&ext=MOV`, picking file with `react-native-camera-roll-picker`

react-native-mov-to-mp4 version: 0.2.3

```
MovToMp4.convertMovToMp4(local_uri, filename)
    .then(results => {
      console.log('success convert')
      console.log(results)
    })
    .catch(err => {
      console.log('MovToMp4 err:')
      console.log(local_uri)
      console.log(filename)
      console.log(err)
    });

MovToMp4 err:
assets-library://asset/asset.MOV?id=1C8F1986-8C2A-407C-8A33-1A44F878FDCB&ext=MOV
734c58a7-8b9c-48a8-b456-6f080e4bd25a.mp4
Error: The operation could not be completed
    at createErrorFromErrorData (NativeModules.js:117)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:354)
    at MessageQueue.js:129
    at MessageQueue.__guard (MessageQueue.js:269)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:128)
    at t (RNDebuggerWorker.js:1)
```

**Comment by taltultc** [comment]
@Andorbal do you have fix for this?

**Comment by taltultc** [comment]
Hey, i rollback some changes, so just update the react-native-mov-to-mp4 and see the new README

**Comment by Kuhne1** [comment]
For anyone who ends up back here. I got this error because I passed in the file with the "file://" prefix.
A simple replace, fixed this error for me.
Pre replace: 
```
let file = "file:///var/mobile/Containers/Data/Application/FE51F4CC-ACDA-4D77-B348-0517F23EB79E/Documents/All/982d8643d95d35627897f89d79bb145d74745a84b738aa0321661d329bfc9aef.mov"

let cleanFile = file.replace('file://','')
```

**Comment by evtuw** [comment]
I have same issue. Any update?

**Comment by taltultc** [comment]
Hi @anhnd11 
I have updated the npm to the new version.

**Comment by MaheshNandam** [comment]
code:EAVFOUNDATIONERRORDOMAIN-11800
message:The operation could not be completed
domain:AVFoundationErrorDomain

trying to convert mov to mp4

mov - "file:///var/mobile/Containers/Data/Application/C6F9E866-68CB-4800-A960-5FCBED4347D1/Library/Caches/Camera/C8011705-0160-4748-B0D1-EA5E20210585.mov"

@taltultc having issue with new version, can you suggest any changes which can help us?

**Comment by evtuw** [comment]
> Hi @anhnd11
> I have updated the npm to the new version.

Thanks @taltultc
