### ISSUE TITLE
 Cannot read property 'convertMovToMp4' of undefined

### ISSUE THREAD

**Issue by Gzbox** [taltultc/react-native-mov-to-mp4#8]
` 

    ImagePicker.showImagePicker(options, (response) => {
      console.log('196 response%o', response)
      if (response.didCancel) {
        return
      } else if (response.uri) {
        console.log('200 uri response%o', response.uri)
        let filename = Date.now().toString()
        let PATH = Platform.OS === 'ios' ? response.uri.replace('file:///', '') : response.uri;
        console.log('MovToMp4:%o', MovToMp4.convertMovToMp4)
        MovToMp4.convertMovToMp4(response.uri, filename + ".mp4", function (results) {
          //here you can upload the video...
          console.log(results)
        })

        this.setState({
          file: filename
        })
        this.uri = PATH
        // console.log('this.uri:%o', this.uri)
        RNFetchBlob.fetch('POST', 'https://content.dropboxapi.com/2/files/upload', {
          // dropbox upload headers
          Authorization: "Bearer access-token...",
          'Dropbox-API-Arg': JSON.stringify({
            path: PATH,
            mode: 'add',
            autorename: true,
            mute: false
          }),
          'Content-Type': 'application/octet-stream',
          // Change BASE64 encoded data to a file path with prefix `RNFetchBlob-file://`.
          // Or simply wrap the file path with RNFetchBlob.wrap().
        }, RNFetchBlob.wrap({ path: PATH }))
          .uploadProgress((written, total) => {
            // 本地查找进度
            console.log('uploaded', written / total)
          })
          .progress((received, total) => {
            let perent = received / total;
            // 上传进度打印
            console.log(perent);
          })
          .then((res) => {
            console.log(res.text())
          })
          .catch((err) => {
            // error handling ..
            console.log('err:%o', err)
          })
      }
    })`

![image](https://user-images.githubusercontent.com/21010051/33535760-916762de-d8ea-11e7-92e5-ebdcab54ace8.png)

How should I solve it?
How should I solve it?
thank you

**Comment by taltultc** [comment]
Hey, 
try to update the react-native-mov-to-mp4

**Comment by snly2386** [comment]
I'm getting the same error - and I'm on the latest version 0.2.1.  Can't get this work. Any suggestions ?

**Comment by snly2386** [comment]
export default {
  convertMovToMp4: function(filename, dest, cb) {
    this line right here is throwing the error => NativemovToMp4.convertMovToMp4(filename, dest, cb);
  }
}

There doesn't appear to be a 'moveToMp4' property on the NativeModules

**Comment by ChristopherJohnson25** [comment]
Getting the same issue here. Any updates?

**Comment by snobear** [comment]
I was having the same issue when running on android. Its a pain to conditionally import libs for iOS vs. Android, and you shouldn't have to. Anyway, I fixed this in my fork and added other fixes to get this working on RN > 0.6x:

https://github.com/snobear/react-native-mov-to-mp4

This is a really handy module that we should keep going!

**Comment by taltultc** [comment]
@snobear can you make a pull request?

**Comment by snobear** [comment]
@taltultc sure thing, thanks for reaching out. See PR #16.
