### ISSUE TITLE
Export session failed

### ISSUE THREAD

**Issue by colewinans** [taltultc/react-native-mov-to-mp4#9]
Using:

- `"react-native": "0.50.3",` 
- `"react-native-mov-to-mp4": "^0.2.1",`
- `"react-native-camera": "^0.12.0",`

When following the README example, I continue to get the following error:

`Export session failed`.

Here's the record function:

```
  startRecording = () => {
    if (this.camera) {
      this.camera.capture({mode: Camera.constants.CaptureMode.video})
          .then((data) => {
            var filename = Date.now().toString();
            MovToMp4.convertMovToMp4(data.path, filename + ".mp4", function (results) {
              //here you can upload the video...
              console.log(results);
            });
          })
          .catch(err => console.error(err));
      this.setState({
        isRecording: true
      });
    }
  }
```

I can confirm that the `data` object is returning properly, and everything else is working as it should.

**Comment by card-b** [comment]
I had the same problem but noticed that my filename was always the same, temp.mp4, and changing each call to something unique like `Date.now().valueOf() + ".mp4"` fixed it.

**Comment by Sangrene** [comment]
@adam-denny he's already changing the name of the file...

Any news on this issue ?

**Comment by groteworld** [comment]
Anyone with an update on this? I'm also experiencing this. 

For others looking at this issue. It is in the xcode console where "Export session failed", but you may notice this bug with characteristics like the callback not being run but no error in metro bundler or the remote js debug console.
